### ISSUE TITLE
Maps dissapearing after generating

### ISSUE THREAD

**Issue by ElMolgajete** [Syrikal/Nether-Map-Port#3]
I was playing with this mod on my modpack and then I've maked a vanilla map, but, when I tried to generate it (open it/use it) the map just dissapeared.
It only happens with this mod installed.
Mod ver: 1.0
Forge: 43.2.4

**Comment by Syrikal** [comment]
Could you give more details as to the _exact_ sequence of events, please? I need to know how to replicate this.

**Comment by ElMolgajete** [comment]
Here's a video of the bug
https://streamable.com/p7xzsk

**Comment by Syrikal** [comment]
Oh you mean the _actual map item_ disappeared, not the image. That's really weird and I have no idea what could be doing that. Thanks for the video.

Would you mind sending me your config file? It might help me out, might not, we'll see. I'll get right on it.

(Incidentally, _after_ you send me a copy, try changing whether overworld maps are enabled or disabled. That'd be my best guess to fix it while I work on a patch.)

**Comment by ElMolgajete** [comment]
Here's the Config file
https://pastebin.com/7azqLvHw

**Comment by Syrikal** [comment]
Alright, found and fixed the bug. The proper workaround for the moment is to _use maps in stacks of at least 2_. This bug only triggers when you use the last map in a stack.

Once I port the fix to the other versions I'll upload them all to CurseForge.
